# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CSP_gui.ui'
#
# Created: Sat Mar 18 17:05:57 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1076, 755)
        self.gridLayout_12 = QtGui.QGridLayout(Dialog)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 383))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_3.addWidget(self.label_15)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.PDB_file_line = QtGui.QLineEdit(self.groupBox_5)
        self.PDB_file_line.setObjectName(_fromUtf8("PDB_file_line"))
        self.horizontalLayout_4.addWidget(self.PDB_file_line)
        self.selectPDBButton = QtGui.QPushButton(self.groupBox_5)
        self.selectPDBButton.setObjectName(_fromUtf8("selectPDBButton"))
        self.horizontalLayout_4.addWidget(self.selectPDBButton)
        self.addFixedButton = QtGui.QPushButton(self.groupBox_5)
        self.addFixedButton.setObjectName(_fromUtf8("addFixedButton"))
        self.horizontalLayout_4.addWidget(self.addFixedButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.seq_entry = QtGui.QTextEdit(self.groupBox_5)
        self.seq_entry.setObjectName(_fromUtf8("seq_entry"))
        self.verticalLayout_2.addWidget(self.seq_entry)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.inputFASTA = QtGui.QRadioButton(self.groupBox_5)
        self.inputFASTA.setObjectName(_fromUtf8("inputFASTA"))
        self.horizontalLayout_5.addWidget(self.inputFASTA)
        self.inputPDB = QtGui.QRadioButton(self.groupBox_5)
        self.inputPDB.setObjectName(_fromUtf8("inputPDB"))
        self.horizontalLayout_5.addWidget(self.inputPDB)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.RVP = QtGui.QLineEdit(self.groupBox_3)
        self.RVP.setObjectName(_fromUtf8("RVP"))
        self.gridLayout.addWidget(self.RVP, 0, 1, 1, 1)
        self.res_spacing = QtGui.QLineEdit(self.groupBox_3)
        self.res_spacing.setObjectName(_fromUtf8("res_spacing"))
        self.gridLayout.addWidget(self.res_spacing, 1, 1, 1, 1)
        self.cutoff = QtGui.QLineEdit(self.groupBox_3)
        self.cutoff.setObjectName(_fromUtf8("cutoff"))
        self.gridLayout.addWidget(self.cutoff, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.MC_steps = QtGui.QLineEdit(self.groupBox_3)
        self.MC_steps.setObjectName(_fromUtf8("MC_steps"))
        self.gridLayout_3.addWidget(self.MC_steps, 1, 1, 1, 1)
        self.opt_step = QtGui.QLineEdit(self.groupBox_3)
        self.opt_step.setObjectName(_fromUtf8("opt_step"))
        self.gridLayout_3.addWidget(self.opt_step, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_2.addWidget(self.label_20)
        self.ionPositive = QtGui.QRadioButton(self.groupBox_3)
        self.ionPositive.setObjectName(_fromUtf8("ionPositive"))
        self.horizontalLayout_2.addWidget(self.ionPositive)
        self.ionNegative = QtGui.QRadioButton(self.groupBox_3)
        self.ionNegative.setObjectName(_fromUtf8("ionNegative"))
        self.horizontalLayout_2.addWidget(self.ionNegative)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.CSR_start = QtGui.QLineEdit(self.groupBox_3)
        self.CSR_start.setObjectName(_fromUtf8("CSR_start"))
        self.gridLayout_2.addWidget(self.CSR_start, 0, 1, 1, 1)
        self.CSR_stop = QtGui.QLineEdit(self.groupBox_3)
        self.CSR_stop.setObjectName(_fromUtf8("CSR_stop"))
        self.gridLayout_2.addWidget(self.CSR_stop, 0, 3, 1, 1)
        self.CSR_step = QtGui.QLineEdit(self.groupBox_3)
        self.CSR_step.setObjectName(_fromUtf8("CSR_step"))
        self.gridLayout_2.addWidget(self.CSR_step, 0, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 4, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.OFN = QtGui.QLineEdit(self.groupBox_3)
        self.OFN.setObjectName(_fromUtf8("OFN"))
        self.horizontalLayout.addWidget(self.OFN)
        self.write_log = QtGui.QCheckBox(self.groupBox_3)
        self.write_log.setObjectName(_fromUtf8("write_log"))
        self.horizontalLayout.addWidget(self.write_log)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.editIntrinsicButton = QtGui.QPushButton(self.groupBox_3)
        self.editIntrinsicButton.setObjectName(_fromUtf8("editIntrinsicButton"))
        self.horizontalLayout_11.addWidget(self.editIntrinsicButton)
        self.run = QtGui.QPushButton(self.groupBox_3)
        self.run.setObjectName(_fromUtf8("run"))
        self.horizontalLayout_11.addWidget(self.run)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_9.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.label_14)
        self.CS_processing_value = QtGui.QLabel(self.groupBox_4)
        self.CS_processing_value.setText(_fromUtf8(""))
        self.CS_processing_value.setObjectName(_fromUtf8("CS_processing_value"))
        self.horizontalLayout_8.addWidget(self.CS_processing_value)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_9.addWidget(self.label_16)
        self.energy_processing_value = QtGui.QLabel(self.groupBox_4)
        self.energy_processing_value.setText(_fromUtf8(""))
        self.energy_processing_value.setObjectName(_fromUtf8("energy_processing_value"))
        self.horizontalLayout_9.addWidget(self.energy_processing_value)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_7.addWidget(self.label_18)
        self.progress_processing_value = QtGui.QLabel(self.groupBox_4)
        self.progress_processing_value.setText(_fromUtf8(""))
        self.progress_processing_value.setObjectName(_fromUtf8("progress_processing_value"))
        self.horizontalLayout_7.addWidget(self.progress_processing_value)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 0, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.opt_plot = PlotWidget(self.groupBox_4)
        self.opt_plot.setObjectName(_fromUtf8("opt_plot"))
        self.horizontalLayout_3.addWidget(self.opt_plot)
        self.freq_plot = PlotWidget(self.groupBox_4)
        self.freq_plot.setObjectName(_fromUtf8("freq_plot"))
        self.horizontalLayout_3.addWidget(self.freq_plot)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_11.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_4, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Specify Simulation Parameters", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Sekect Input Type", None))
        self.label_15.setText(_translate("Dialog", "Select PDB file", None))
        self.selectPDBButton.setText(_translate("Dialog", "Browse", None))
        self.addFixedButton.setText(_translate("Dialog", "Add Fixed Charge", None))
        self.label.setText(_translate("Dialog", "Sequence", None))
        self.inputFASTA.setText(_translate("Dialog", "Linear", None))
        self.inputPDB.setText(_translate("Dialog", "PDB", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Parameters", None))
        self.label_3.setText(_translate("Dialog", "Residue Spacing (A)", None))
        self.label_4.setText(_translate("Dialog", "Energy Cutoff (kcal/mol)", None))
        self.label_2.setText(_translate("Dialog", "Dielectric Constant", None))
        self.label_8.setText(_translate("Dialog", "Optimisation Steps", None))
        self.label_9.setText(_translate("Dialog", "Iterations", None))
        self.label_20.setText(_translate("Dialog", "Ion Polarity", None))
        self.ionPositive.setText(_translate("Dialog", "Positive", None))
        self.ionNegative.setText(_translate("Dialog", "Negative", None))
        self.label_17.setText(_translate("Dialog", "Charge State Range", None))
        self.label_5.setText(_translate("Dialog", "Start", None))
        self.label_6.setText(_translate("Dialog", "   Stop", None))
        self.label_7.setText(_translate("Dialog", "   Step", None))
        self.label_10.setText(_translate("Dialog", "Output File", None))
        self.write_log.setText(_translate("Dialog", "Write Log File", None))
        self.editIntrinsicButton.setText(_translate("Dialog", "Edit GB/GA Intrinsic Values", None))
        self.run.setText(_translate("Dialog", "Run Simulation", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Results", None))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Processing charge state:</span></p></body></html>", None))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Current energy is:</span></p></body></html>", None))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Progress:</span></p></body></html>", None))
        self.label_11.setText(_translate("Dialog", "Optimisation Plot", None))
        self.label_12.setText(_translate("Dialog", "GBapp/GAapp vs Charge State", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

